import { CountryConfig } from '@/types';

export const countries: CountryConfig[] = [
  {
    code: 'US',
    name: 'United States',
    currency: 'USD',
    currencySymbol: '$',
    defaultRate: 6.5,
    taxDeductionRate: 25,
    avgPropertyTax: 1.1,
    avgInsurance: 0.35,
    loanTermOptions: [15, 20, 30],
  },
  {
    code: 'UK',
    name: 'United Kingdom',
    currency: 'GBP',
    currencySymbol: '£',
    defaultRate: 4.75,
    taxDeductionRate: 20,
    avgPropertyTax: 1.5,
    avgInsurance: 0.15,
    loanTermOptions: [15, 20, 25, 30],
  },
  {
    code: 'DE',
    name: 'Germany',
    currency: 'EUR',
    currencySymbol: '€',
    defaultRate: 3.5,
    taxDeductionRate: 0,
    avgPropertyTax: 1.5,
    avgInsurance: 0.3,
    loanTermOptions: [10, 15, 20, 25, 30],
  },
  {
    code: 'CA',
    name: 'Canada',
    currency: 'CAD',
    currencySymbol: 'C$',
    defaultRate: 5.25,
    taxDeductionRate: 25,
    avgPropertyTax: 1.0,
    avgInsurance: 0.4,
    loanTermOptions: [15, 20, 25, 30],
  },
  {
    code: 'AU',
    name: 'Australia',
    currency: 'AUD',
    currencySymbol: 'A$',
    defaultRate: 6.2,
    taxDeductionRate: 30,
    avgPropertyTax: 0.5,
    avgInsurance: 0.25,
    loanTermOptions: [15, 20, 25, 30],
  },
  {
    code: 'JP',
    name: 'Japan',
    currency: 'JPY',
    currencySymbol: '¥',
    defaultRate: 1.5,
    taxDeductionRate: 0,
    avgPropertyTax: 1.2,
    avgInsurance: 0.2,
    loanTermOptions: [10, 15, 20, 25, 30, 35],
  },
  {
    code: 'IN',
    name: 'India',
    currency: 'INR',
    currencySymbol: '₹',
    defaultRate: 8.5,
    taxDeductionRate: 30,
    avgPropertyTax: 0.5,
    avgInsurance: 0.1,
    loanTermOptions: [5, 10, 15, 20, 25],
  },
  {
    code: 'BR',
    name: 'Brazil',
    currency: 'BRL',
    currencySymbol: 'R$',
    defaultRate: 9.5,
    taxDeductionRate: 0,
    avgPropertyTax: 1.0,
    avgInsurance: 0.15,
    loanTermOptions: [10, 15, 20, 25, 30],
  },
];

export const loanTypes = [
  { id: 'mortgage', name: 'Home Mortgage', icon: '🏠', description: 'Real estate purchase financing' },
  { id: 'personal', name: 'Personal Loan', icon: '💰', description: 'Unsecured personal financing' },
  { id: 'auto', name: 'Auto Loan', icon: '🚗', description: 'Vehicle purchase financing' },
  { id: 'business', name: 'Business Loan', icon: '🏢', description: 'Commercial enterprise financing' },
  { id: 'student', name: 'Student Loan', icon: '🎓', description: 'Education financing' },
];

export const getCountryConfig = (code: string): CountryConfig => {
  return countries.find((c) => c.code === code) || countries[0];
};
